### ISSUE TITLE
Error when using decompressFromBase64()

### ISSUE THREAD

**Issue by phuwin** [diogoduailibe/lzstring4j#4]
My Base64:
`N4IgxgpiBcDaoEsawIwAYCc6DsBmANAGxoB0ArAExkAcK1+VJhKKFu9ALGvthfgdTRoAuvhAAXZKnzcyI/LAIA7AK4AbNfyHDhAX3yJk6LGmwcipSjToMyTFm3oo5RAgO1jJcabPmL8qhpaInoGIEhwxjhkFuRUtPSMzKzsDNjcvPz4gvISUigy+HKi/oGauNp6oiAaMDEgALbiXhRcYggAJjAgAFJKagDWhNQAyigAEiBiAOYwKBzYKMR4FHwgAG4AhnNi6xAATjs1St0AggDOAwD2apubGgD6auJQYmoN3Q1XAEYICGoIF7ncSbFTnUHiK4NO7iBBXAACEAB4JIADMkJ5zlIQKjxAAHKY4/FolRKCDiNEYkCbJRXJQATy+YMJUwoBRAAHoOhB1hzCSgAOIAITK/OFZQAqgAZKbmZxFHS6IA===`
The error:
```
java.lang.StringIndexOutOfBoundsException: length=162; index=162
at java.lang.String.charAt(Native Method)
at external.qrcompressor.LZString.decompress(LZString.java:365)
at external.qrcompressor.LZString.decompressFromBase64(LZString.java:624)
```
What's the problem? I use lzstring.js and it can decompress it.
http://185.26.50.123/lzstring/

**Comment by diogoduailibe** [comment]
Hi Phu Nguyen,

So, i visited the page where you using it and i found out that the version of your lzstring javascript library is 1.4.4. This project that i created works for the version 1.3.3. So, you have two fast solutions:
- Downgrade your javascript library to 1.3.3 or
- Use Rufushuang Java Library: https://github.com/rufushuang/lz-string4java. It's on the version that you are using.

Hope you can find the best solution for this.
